SELECT first_name||' '||last_name AS "이름", email AS "이메일", phone_number AS "전화번호" FROM EMPLOYEES ORDER BY HIRE_DATE ASC;

SELECT job_title, max_salary FROM JOBS ORDER BY MAX_SALARY DESC;

SELECT count(*) FROM EMPLOYEES WHERE MANAGER_ID is null;

SELECT JOB_TITLE FROM JOBS ORDER BY JOB_TITLE DESC, MAX_SALARY DESC;

SELECT count(*) FROM DEPARTMENTS;

SELECT * FROM DEPARTMENTS ORDER BY length(DEPARTMENT_NAME) DESC;

SELECT count(*) FROM DEPARTMENTS WHERE MANAGER_ID is null;

SELECT upper(COUNTRY_NAME) FROM COUNTRIES ORDER BY COUNTRY_NAME ASC;

SELECT * FROM REGIONS ORDER BY length(REGION_NAME) ASC;

SELECT DISTINCT(lower(CITY)) AS CITY FROM LOCATIONS ORDER BY CITY ASC;