--문제풀이 집계

SELECT MAX(SALARY) AS "최고임금", MIN(SALARY) AS "최저임금", MAX(SALARY) - MIN(SALARY) AS "최고임금-최저임금" FROM EMPLOYEES;

SELECT to_char(MAX(HIRE_DATE), 'yyyy"년" mm"월" dd"일') FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES GROUP BY department_id ORDER BY AVG(SALARY) DESC, MAX(SALARY) DESC, MIN(SALARY) DESC;

SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID ORDER BY AVG(SALARY) DESC, MAX(SALARY) DESC, MIN(SALARY) DESC;

SELECT to_char(MIN(HIRE_DATE), 'yyyy"년" mm"월" dd"일') FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY), MIN(SALARY), AVG(SALARY)-MIN(SALARY) FROM EMPLOYEES group by DEPARTMENT_ID HAVING AVG(SALARY)-MIN(SALARY) < 2000 ORDER BY AVG(SALARY)-MIN(SALARY) DESC;

SELECT MAX_SALARY-MIN_SALARY FROM JOBS ORDER by MAX_SALARY-MIN_SALARY desc;
SELECT JOB_TITLE FROM JOBS WHERE MAX_SALARY-MIN_SALARY = 19920;